//
//  MemberwiseInitializer.swift
//  InterviewPrep
//
//  Created by Akhilesh Rathor on 30/06/25.
//
/*
 6. Memberwise Initializers (for Structures):-
 
 If a struct does not define any custom initializer, Swift automatically gives it a memberwise initializer that takes values for each stored property without default values.
 */
import UIKit

class MemberwiseInitializer: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        // Memberwise init is auto-generated by Swift:
        let user = User(name: "John", age: 25)
        print(user.age, user.name)
        let user1 = User1(name: "akhilesh")
        print(user1.age, user1.name)
    }
    

}
struct User {
    var name: String
    var age: Int
}

struct User1 {
    var name: String
    var age: Int

    init(name: String) {
        self.name = name
        self.age = 18
    }
}

// ❌ Now you cannot use: User(name: "John", age: 25) — missing memberwise initializer
